// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "events" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function EventsSection(): React.JSX.Element {
  return (
    <div id="events" data-section="events">
        <SectionErrorBoundary name="events">
              <FeaturesRevealCardsBento
          tag="Join the Celebration"
          title="Upcoming Events"
          description="Don't miss the ultimate social nights at Barelo."
          items={[
            {
              title: "Salsa Saturdays",
              description: "Live DJs, dancing, and high-energy nights.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/couple-celebrating-new-year-s-eve-each-other-s-arms_23-2150901996.jpg",
            },
            {
              title: "Happy Hour",
              description: "Drink specials and premium bites.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/view-cocktail-beverage-glass-with-abstract-neo-futuristic-set_23-2150938353.jpg",
            },
            {
              title: "Latin Nights",
              description: "The best social music experience.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/couple-staying-light-no-war-wording_23-2149377320.jpg",
            },
            {
              title: "Private Parties",
              description: "Book us for your special occasion.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/wonderful-wedding-table-amazing-restaurant_8353-9875.jpg",
            },
            {
              title: "Live Music",
              description: "Top Latin artists performing weekly.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/man-singing-retro-microphone_107420-96133.jpg",
            },
            {
              title: "Sunday Brunch",
              description: "Recover with flavor.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/side-view-breakfast-set-azerbaijani-style-eggs-with-tomatoes-toast-jam-honey-fresh-tomato-cucumber-cheese-french-bread-rolls-black-tea-cup_141793-3604.jpg",
            },
            {
              title: "VIP Night",
              description: "Exclusive table service experience.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/dark-vip-cinema-studio-still-life_23-2149500612.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
