// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "experience" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ExperienceSection(): React.JSX.Element {
  return (
    <div id="experience" data-section="experience">
        <SectionErrorBoundary name="experience">
              <AboutTextSplit
          title="More Than a Restaurant"
          descriptions={[
            "At Barelo, every night feels like a celebration. Whether you're joining us for Happy Hour, dinner with friends, or date night, we create an atmosphere where food, music, and community come together.",
            "Our Latin percussion, candlelight cocktails, and upscale decor provide the perfect backdrop for creating lasting memories in Kissimmee.",
          ]}
          primaryButton={{
            text: "See Gallery",
            href: "#",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
