// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroTiltedCards from '@/components/sections/hero/HeroTiltedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroTiltedCards
          tag="Kissimmee's Premier Destination"
          title="Barelo Bar & Grill"
          description="Experience the perfect fusion of Colombian and Dominican cuisine, handcrafted cocktails, live music, and the vibrant energy of Latin nightlife."
          primaryButton={{
            text: "Reserve a Table",
            href: "#contact",
          }}
          secondaryButton={{
            text: "View Menu",
            href: "#menu",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/woman-enjoying-her-virtual-date_23-2149307269.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/friends-posing-embraced-new-years_23-2148349097.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/shrimp-plate-garnished-with-sauce-bread-stuffing-spinach-shredded-carrot_141793-2276.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/young-friends-hug-night-funfair_23-2148281658.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/handsome-african-american-man-posing-inside-night-club-black-hat_627829-5507.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
