// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "menu" section.

import React from 'react';
import PricingMediaCards from '@/components/sections/pricing/PricingMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MenuSection(): React.JSX.Element {
  return (
    <div id="menu" data-section="menu">
        <SectionErrorBoundary name="menu">
              <PricingMediaCards
          tag="Taste the Passion"
          title="Signature Menu"
          description="Traditional recipes with a modern flair."
          plans={[
            {
              tag: "Dominican",
              price: "Mofongo",
              period: "Classic",
              features: [
                "Savory",
                "Authentic",
                "Comforting",
              ],
              primaryButton: {
                text: "Reserve Now",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/still-life-recipe-with-plantain_23-2151062828.jpg",
            },
            {
              tag: "Colombian",
              price: "Bandeja",
              period: "Traditional",
              features: [
                "Home-style",
                "Bold Flavors",
                "Hearty",
              ],
              primaryButton: {
                text: "Reserve Now",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-beans-sausages-dish_23-2148725027.jpg",
            },
            {
              tag: "Cocktails",
              price: "Leches",
              period: "Martini",
              features: [
                "Signature",
                "Sweet",
                "Smooth",
              ],
              primaryButton: {
                text: "Reserve Now",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/lemon-drop-martini-cocktail-isolated-white-background_123827-24016.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
