// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import { Music, Star, Wine } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsIconCards
          tag="By The Numbers"
          title="The Barelo Impact"
          description="Delivering excellence one night at a time."
          metrics={[
            {
              icon: Star,
              title: "Happy Guests",
              value: "10K+",
            },
            {
              icon: Music,
              title: "Live Nights",
              value: "500+",
            },
            {
              icon: Wine,
              title: "Cocktails Served",
              value: "50K+",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
