// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeCards
          tag="Guest Voices"
          title="What Our Guests Say"
          description="Authentic experiences from our vibrant community."
          testimonials={[
            {
              name: "Sarah J.",
              role: "Foodie",
              quote: "Great vibe and atmosphere. Loved the music.",
              imageSrc: "http://img.b2bpic.net/free-photo/adults-enjoying-mexican-food_23-2149663829.jpg",
            },
            {
              name: "Michael C.",
              role: "Local",
              quote: "The menu was a mix of Colombian & Dominican food. Really enjoyable.",
              imageSrc: "http://img.b2bpic.net/free-photo/couple-eating-drinking-wine-with-woman-foreground-festive-dinner-kitchen-talking-happy-sitting-table-dining-room-enjoying-meal-home-having-romantic-time-candle-lights_482257-3617.jpg",
            },
            {
              name: "Emily R.",
              role: "Visitor",
              quote: "Music 10/10. The Happy Hour exceeded my expectations.",
              imageSrc: "http://img.b2bpic.net/free-photo/people-cheering-drinking-beer-while-playing-beer-pong-indoor-party_23-2149431385.jpg",
            },
            {
              name: "David K.",
              role: "Regular",
              quote: "Super chill environment, friendly staff and great food.",
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-shot-handsome-male-smiling_181624-41237.jpg",
            },
            {
              name: "Maria L.",
              role: "Dancer",
              quote: "Best salsa night in Kissimmee, hands down.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-friends-having-fun-party_23-2150188408.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
