// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "why-barelo" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function WhyBareloSection(): React.JSX.Element {
  return (
    <div id="why-barelo" data-section="why-barelo">
        <SectionErrorBoundary name="why-barelo">
              <FeaturesBentoGrid
          tag="The Barelo Experience"
          title="Why Everyone Loves Barelo"
          description="Authentic Latin roots meet sophisticated nightlife vibes."
          features={[
            {
              title: "Signature Cocktails",
              description: "Crafted by expert mixologists with premium ingredients.",
              imageSrc: "http://img.b2bpic.net/free-photo/full-length-stock-photo-extremely-trendy-luxurious-brunette-model-crop-top-silver-sparkling-jacket-black-trousers-high-heels-model-trendy-outfit-sitting-bar-stool-club-bar_132075-8989.jpg",
            },
            {
              title: "Live Latin Nights",
              description: "Salsa, DJs, and unforgettable weekends.",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-passionate-dancers-dancing_158595-4671.jpg",
            },
            {
              title: "Authentic Cuisine",
              description: "Colombian & Dominican dishes made with love.",
              imageSrc: "http://img.b2bpic.net/free-photo/shrimp-soup-rice-frame_23-2148725073.jpg",
            },
            {
              title: "VIP Ambience",
              description: "Safe, stylish, and high-energy atmosphere.",
              imageSrc: "http://img.b2bpic.net/free-photo/elegant-beautiful-woman-sitting-vintage-cafe-black-velvet-dress-evening-gown-rich-stylish-lady-elegant-fashion-trend-sexy-seductive-look-attractive-skinny-figure_285396-7236.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
